config/routes.rb
FuelTracker::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :vehicles
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { email.downcase! }
	before_create :create_remember_token

	has_many :vehicles, dependent: :destroy

	validates :name,  presence: true, length: { maximum: 50 }
    #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i	
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
				uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 6 }

	has_secure_password

    def User.new_remember_token
      SecureRandom.urlsafe_base64
    end

    def User.encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
    end

    def feed
    	#Vehicle.where("user_id = ?", id)
    	vehicles
    	# change to fillups
    end

	private

	  def create_remember_token
	    self.remember_token = User.encrypt(User.new_remember_token)
	  end

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order('year DESC') }
	validates :name, presence: true
	validates :make, presence: true
	validates :model, presence: true
	validates :year, presence: true
	validates :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
	  user = User.find_by(email: params[:session][:email].downcase)
	  if user && user.authenticate(params[:session][:password])
	  	sign_in user
	  	redirect_back_or user
	  else
        flash.now[:error] = 'Invalid email/password combination'
	    render 'new'
	  end
	end

	def destroy
	  sign_out
	  redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		@vehicle = current_user.vehicles.build
  		@vehicles = current_user.vehicles.paginate(page: params[:page])
  		@feed_items = current_user.feed.paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]
  before_action :existing_user, only: [:new, :create]

  def new
  	@user = User.new
  end

  def create
	@user = User.new(user_params)
	if @user.save
		sign_in @user
		flash[:success] = "Welcome to the Fuel Tracker! Servicing all your fuel tracking needs!"
		redirect_to @user
	else
		render 'new'
	end
  end

  def destroy
  	@user = User.find(params[:id])
  	unless current_user?(@user)
  		@user.destroy
  		flash[:success] = "User deleted"
  	else
  		flash[:error] = "Administrators cannot destroy themselves"
  	end
  	redirect_to users_url
  end

  def edit
  end

  def update
  	if @user.update_attributes(user_params)
  	  flash[:success] = "Profile updated"
  	  redirect_to @user
  	else
  	  render 'edit'
  	end
  end

  def show
  	@user = User.find(params[:id])
  	@vehicles = @user.vehicles.paginate(page: params[:page])
  end

  def index
  	@users = User.paginate(page: params[:page])
  end

  private

    def user_params
    	params.require(:user).permit(:name, :email, :password,
    								:password_confirmation)
    end

    # Before filters

    def correct_user
    	@user = User.find(params[:id])
    	redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
    	redirect_to(root_url) unless current_user.admin?
    end

    def existing_user
    	redirect_to(root_url) if signed_in?
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
	before_action :signed_in_user
	before_action :correct_user, only: :destroy

	def show
	  @vehicle = Vehicle.find(params[:id])
	end

	def new
	  @vehicle = Vehicle.new
	end

	def create
		@vehicle = current_user.vehicles.build(vehicle_params)
		if @vehicle.save
			flash[:success] = "Vehicle created!"
			redirect_to @vehicle
		else
			render 'new'
		end
	end

	def destroy
		@vehicle.destroy
		redirect_to root_url
	end

	def edit
	end

	def update
	end
 
 	private

    	def vehicle_params
    		params.require(:vehicle).permit(:name, :make, :model, :year, :odometer)
    	end

    	def correct_user
    		@vehicle = current_user.vehicles.find_by(id: params[:id])
    		redirect_to root_url if @vehicle.nil?
    	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Fuel Tracker"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
        self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token)) unless current_user.nil?
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies.permanent[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

    def signed_in_user
    	unless signed_in?
    	  store_location
    	  redirect_to signin_url, notice: "Please sign in"
    	end
    end	

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 40 } )
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar", size: size)
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.google.ca?q=Sean+White#q=Sean+White/">Fuel Tracker</a>
    by Sean White
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Fuel Tracker", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>    	
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="vehicles">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="name"><%= feed_item.name %></span>
  <span class="timestamp">
    Fueled up <%= time_ago_in_words(feed_item.updated_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure bout this cap'n?" },
                                     title: feed_item.name %>
  <% end %>  
</li>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.vehicles.count, "vehicle") %>
</span>

app/views/shared/_vehicle_list.html.erb
<% if @vehicles.any? %>
  <h3>Vehicles (<%= @vehicles.count %>)</h3>
  <ol class="vehicles">
    <%= render @vehicles %>
  </ol>
  <%= will_paginate @vehicles %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>Fuel Tracker is an app used to track fuel usage and calculate 
   consumption statistics for all of your vehicles.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Fuel Tracker Master about this app at this
  <a href="http://www.google.ca?q=go+fuck+yourself#q=go+fuck+yourself">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Sorry, there is no help. You're on your own.</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/vehicle_list' %>
      </section>
    </aside>
	<div class="span8">
      <h3>Latest Fillups</h3>
      <%= render 'shared/feed' %>
    </div>    
  </div>
<% else %>
	<div class="center hero-unit">
		<h1>Fuel Tracker</h1>

		<h2>
			Where did all me fuel go yo?
		</h2>

		<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-success" %>
	</div>

	<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>	
<% end %>	

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%=render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <% if @user.vehicles.any? %>
      <h3>Vehicles (<%= @user.vehicles.count %>)</h3>
      <ol class="vehicles">
        <%= render @vehicles %>
      </ol>
      <%= will_paginate @vehicles %>
    <% end %>
  </div>  
  <%= link_to "Add vehicle", new_vehicle_path, class: "btn btn-large btn-success" %>
</div>

app/views/vehicles/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name, value: 'My New Vehicle' %>

<%= f.label :make %>
<%= f.text_field :make %>

<%= f.label :model %>
<%= f.text_field :model %>

<%= f.label :year %>
<%= f.number_field :year, value: Time.now.year, in: 1900..(Time.now.year+1) %>

<%= f.label :odometer %>
<%= f.number_field :odometer %>

app/views/vehicles/_vehicle.html.erb
<li id="vehicle_<%= vehicle.id %>">
  <span class="name"><%= link_to vehicle.name, vehicle %></span>
  <span class="timestamp">
    Last filled up <%= time_ago_in_words(vehicle.updated_at) %> ago.
  </span>
  <% if current_user?(vehicle.user) %>
  	<%= link_to "delete", vehicle, method: :delete, 
  								   data: { confirm: "You sure bout this cap'n?" },
                                   title: vehicle.name %>
  <% end %>
</li>

app/views/vehicles/new.html.erb
<% provide(:title, 'Add Vehicle') %>
<h1>Add Vehicle</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@vehicle) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Add Vehicle", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/vehicles/show.html.erb
<% provide(:title, @vehicle.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @vehicle.user %>
        <%= @vehicle.user.name %>
      </h1>
    </section>
  </aside>
  <div class="span8">
    <ul class="vehicles">
      <li><h3><%= @vehicle.name %><h3></li>
      <li><%= @vehicle.year %> <%= @vehicle.make %> <%= @vehicle.model %></li>
      <li><%= @vehicle.odometer %> km</li>
    </ul>
  </div>  
  <%= link_to "Add Fillup", '#', class: "btn btn-large btn-success" %>
</div>